import os
import time
from github import Github, GithubException
from typing import Optional

def create_figma_update_pr(
    file_path: str,
    content: str,
    file_name: str,
    figma_file_key: str
) -> Optional[str]:
    """
    Automates the creation of a GitHub branch and Draft PR for a Figma update.
    Returns the URL of the created PR or None if failed.
    """
    token = os.getenv("GITHUB_TOKEN")
    repo_name = os.getenv("GITHUB_REPO") # format: "owner/repo"
    
    if not token or not repo_name:
        print("[GitHub Automation] Missing GITHUB_TOKEN or GITHUB_REPO in environment")
        return None

    try:
        g = Github(token)
        repo = g.get_repo(repo_name)
        
        # 1. Consistent branch name (reuse existing branch for same file)
        # Unique enough to be per-file, but stable across updates
        branch_name = f"automation/figma-{figma_file_key[:8]}"
        
        # 2. Get the default branch (usually main or master)
        main_branch = repo.get_branch(repo.default_branch)
        
        # 3. Create or Get the branch
        try:
            repo.get_branch(branch_name)
            # Branch exists, we will update it
        except GithubException:
            # Branch doesn't exist, create it from default
            repo.create_git_ref(ref=f"refs/heads/{branch_name}", sha=main_branch.commit.sha)
        
        # 4. Create or Update the file on this branch
        commit_message = f"feat(design): Update {file_name} from Figma"
        
        try:
            # Check if file exists to get its SHA (required for updates)
            contents = repo.get_contents(file_path, ref=branch_name)
            repo.update_file(
                path=file_path,
                message=commit_message,
                content=content,
                sha=contents.sha,
                branch=branch_name
            )
        except GithubException as e:
            if e.status == 404:
                # File doesn't exist, create it
                repo.create_file(
                    path=file_path,
                    message=commit_message,
                    content=content,
                    branch=branch_name
                )
            else:
                raise e

        # 5. Check for existing PR to avoid spam
        existing_prs = repo.get_pulls(state='open', head=f"{repo.owner.login}:{branch_name}")
        if existing_prs.totalCount > 0:
            # PR already exists, we just updated the branch, so it's auto-updated.
            pr = existing_prs[0]
            print(f"[GitHub Automation] Updated existing PR: {pr.html_url}")
            return pr.html_url

        # 6. Create Draft Pull Request if none exists
        pr_body = f"""
### 🎨 Figma Design Update
**File:** {file_name}
**Key:** `{figma_file_key}`

This PR was automatically generated from a Figma webhook update. 
Review the generated code and merge when ready.

---
_Generated by MCP Figma Automation_
        """
        
        pr = repo.create_pull(
            title=f"[Figma] Design Update: {file_name}",
            body=pr_body,
            head=branch_name,
            base=repo.default_branch,
            draft=True
        )
        
        return pr.html_url

    except Exception as e:
        print(f"[GitHub Automation] Error: {str(e)}")
        return None
